server:
  port: 2333
  address: 0.0.0.0


lavalink:
  server:
    password: "SIMPERO123"

    sources:
      youtube: false
      soundcloud: true
      http: true
      bandcamp: true
      twitch: true
      vimeo: true
      local: false

    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    trackStuckThresholdMs: 10000


  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"


plugins:
  youtube:
    enabled: true

    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    clients:
      - MUSIC
      - MWEB
      - ANDROID_VR


logging:
  level:
    root: INFO
    lavalink: INFO
