# Ten Dockerfile buduje osobną usługę - serwer Lavalink (nie bota!).
# Na Railway: nowa usługa w tym samym projekcie, "Root Directory" ustawione na "lavalink".
FROM ghcr.io/lavalink-devs/lavalink:4

COPY application.yml /opt/Lavalink/application.yml

EXPOSE 2333
